#get customer by id
GET http://localhost:8080/test
Accept: application/json

###
#get customer by id
GET http://localhost:8080/customers/4
Accept: application/json

###
#get all customer
GET http://localhost:8080/customers/getAll
Accept: application/json

###

#create customer
POST http://localhost:8080/customers/create?name=Tor&lastName=Klerd
Accept: application/json

###

#update customer id
POST http://localhost:8080/customers/update/4
Content-Type: application/json

{
    "nameProduct":"Dilly",
    "priceProduct":"Keen"
}

###
